version: '3.7'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
        - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ${MYSQL_DB_FILE:-/var/otrrent/db}:/var/lib/mysql
    networks:
      - ${APP_NETWORK:-otrrent}

  api:
    build:
      context: ./api
    image: otrrentapi:local
    container_name: otrrentapi
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      FLASK_APP: ${FLASK_APP:-app.py}
      FLASK_ENV: ${FLASK_ENV:-production}
    volumes:
      - ${LOG_PATH}:/opt/app/log
    networks:
      - ${APP_NETWORK:-otrrent}
    depends_on:
      - db

networks:

  otrrent:
    #internal: true
    name: ${APP_NETWORK:-otrrent}
